# Site settings
name: 龚柯
location: 杭州
company: 新华移动
position: 前端工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 18768144918
email: gongkegogogo@gmail.com

baseurl: "/tok-gogogo.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

